### ISSUE TITLE
Does not build against recent xerces-c libs

### ISSUE THREAD

**Issue by stefanhusmann** [nassibnassar/amberfish#1]
Under Arch Linux we have xerces-c 3.2.0, but 3.2.1 does not change things: amberfish won't build.
[buildlog.zip](https://github.com/nassibnassar/amberfish/files/1822490/buildlog.zip)

**Comment by nassibnassar** [comment]
Could you change this line in `src/Makefile.in`:
`CXXFLAGS =      -ansi ${FLAGS} @CPPFLAGS@`
to:
`CXXFLAGS =      --std=c++11 ${FLAGS} @CPPFLAGS@`

Then:
`$ ./configure && make clean all`

**Comment by stefanhusmann** [comment]
Great, works fine!
